//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetsTheBest.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bets
    {
        public int Id { get; set; }
        public int betEventId { get; set; }
        public string userId { get; set; }
        public float amount { get; set; }
        public string state { get; set; }
        public string betType { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual SportEvents SportEvents { get; set; }
    }
}
