//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetsTheBest.Content
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AspNetUsers> AspNetUsers { get; set; }
        public DbSet<Bets> Bets { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Payments> Payments { get; set; }
        public DbSet<Results> Results { get; set; }
        public DbSet<SportEvents> SportEvents { get; set; }
    }
}
