//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetsTheBest.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportEvents
    {
        public SportEvents()
        {
            this.Bets = new HashSet<Bets>();
            this.Results = new HashSet<Results>();
        }
    
        public int Id { get; set; }
        public string command1 { get; set; }
        public string command2 { get; set; }
        public string gameType { get; set; }
        public System.DateTime date { get; set; }
        public string tournament { get; set; }
        public Nullable<float> firstWin { get; set; }
        public Nullable<float> secondWin { get; set; }
        public Nullable<float> gameTie { get; set; }
        public Nullable<float> tieByFirst { get; set; }
        public Nullable<float> tieBySecond { get; set; }
        public Nullable<float> overallTie { get; set; }
        public Nullable<float> total { get; set; }
        public Nullable<float> b { get; set; }
        public Nullable<float> m { get; set; }
        public string state { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual ICollection<Bets> Bets { get; set; }
        public virtual ICollection<Results> Results { get; set; }
    }
}
